import type { ComponentType } from 'react';
import {
  // Ícones originais
  Trophy,
  ShieldCheck,
  Heartbeat,
  MapTrifold,
  Timer,
  Star,
  FlagBanner,
  Medal,
  Mountains,
  Waves,
  Lightning,
  UsersThree,
  FireSimple,
  GlobeHemisphereWest,
  MusicNotes,
  Camera,
  MedalMilitary,
  PersonSimpleRun,
  // Ícones adicionais populares
  Heart,
  MapPin,
  Clock,
  Calendar,
  CheckCircle,
  XCircle,
  Warning,
  Info,
  Question,
  Bell,
  Book,
  Bookmark,
  Briefcase,
  Building,
  Car,
  Coffee,
  Compass,
  CreditCard,
  Crown,
  Diamond,
  Envelope,
  Eye,
  FileText,
  FilmReel,
  Flag,
  Gift,
  Globe,
  Handshake,
  House,
  Image,
  Key,
  Lightbulb,
  Lock,
  MagnifyingGlass,
  Megaphone,
  Money,
  Package,
  PaperPlane,
  Phone,
  Play,
  Plus,
  ShoppingBag,
  ShoppingCart,
  Smiley,
  Sparkle,
  Target,
  ThumbsUp,
  Ticket,
  Tree,
  Truck,
  Umbrella,
  User,
  Users,
  Wallet,
  // Esportes
  Basketball,
  SoccerBall,
  Volleyball,
  TennisBall,
  Baseball,
  Football,
  // Outros
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  CaretRight,
  CaretLeft,
  CaretUp,
  CaretDown,
  Check,
  X,
  PlusCircle,
  MinusCircle,
  Pencil,
  Trash,
  Download,
  Upload,
  Share,
  Copy,
  Link,
  LockKey,
  Unlock,
  EyeSlash,
  BellSlash,
  HeartStraight,
  StarHalf,
  // Mais ícones
  Airplane,
  Anchor,
  Apple,
  Atom,
  Bank,
  Bicycle,
  Binoculars,
  Bluetooth,
  Boat,
  Bug,
  Calculator,
  CalendarBlank,
  CameraSlash,
  CarSimple,
  Cards,
  ChartLine,
  ChatCircle,
  Circle,
  Clipboard,
  ClockClockwise,
  Cloud,
  Code,
  CoffeeBean,
  Command,
  CompassTool,
  ComputerTower,
  Confetti,
  Cookie,
  CopySimple,
  Cpu,
  Crosshair,
  Cube,
  CurrencyCircleDollar,
  Database,
  Desktop,
  DeviceMobile,
  DotsThree,
  DotsThreeCircle,
  DotsThreeOutline,
  DownloadSimple,
  Drop,
  Ear,
  Eject,
  Elevator,
  EnvelopeOpen,
  Equals,
  Export,
  EyeClosed,
  Faders,
  FadersHorizontal,
  FastForward,
  FastForwardCircle,
  File,
  FileArrowDown,
  FileArrowUp,
  FileCode,
  FileCsv,
  FileDoc,
  FileImage,
  FilePdf,
  FilePpt,
  FileVideo,
  FileXls,
  FileZip,
  Files,
  FilmStrip,
  Fingerprint,
  FirstAid,
  FirstAidKit,
  Fish,
  FlagCheckered,
  FloppyDisk,
  Flower,
  Folder,
  FolderOpen,
  ForkKnife,
  Funnel,
  GameController,
  GasPump,
  Gear,
  Gif,
  GithubLogo,
  GoogleLogo,
  GraduationCap,
  GridFour,
  Hamburger,
  Hand,
  HandFist,
  HardDrive,
  Hash,
  Headphones,
  HeartBreak,
  Highlighter,
  IdentificationCard,
  ImageSquare,
  InstagramLogo,
  Intersect,
  Jeep,
  Keyhole,
  Ladder,
  Lamp,
  Laptop,
  Leaf,
  Lifebuoy,
  LightbulbFilament,
  LightningSlash,
  LineSegment,
  LinkBreak,
  LinkSimple,
  LinkSimpleBreak,
  LinkedinLogo,
  List,
  ListBullets,
  ListChecks,
  ListDashes,
  ListNumbers,
  ListPlus,
  LockLaminated,
  LockSimple,
  LockSimpleOpen,
  MagicWand,
  Magnet,
  MagnifyingGlassMinus,
  MagnifyingGlassPlus,
  MapPinLine,
  Martini,
  MathOperations,
  Microphone,
  MicrophoneSlash,
  MicrosoftExcelLogo,
  MicrosoftPowerpointLogo,
  MicrosoftWordLogo,
  Minus,
  MoneyWavy,
  Monitor,
  Moon,
  MoonStars,
  Motorcycle,
  Mouse,
  MouseSimple,
  MusicNote,
  Newspaper,
  Note,
  NoteBlank,
  NotePencil,
  Notification,
  NumberCircleEight,
  NumberCircleFive,
  NumberCircleFour,
  NumberCircleNine,
  NumberCircleOne,
  NumberCircleSeven,
  NumberCircleSix,
  NumberCircleThree,
  NumberCircleTwo,
  NumberCircleZero,
  NumberEight,
  NumberFive,
  NumberFour,
  NumberNine,
  NumberOne,
  NumberSeven,
  NumberSix,
  NumberSquareEight,
  NumberSquareFive,
  NumberSquareFour,
  NumberSquareNine,
  NumberSquareOne,
  NumberSquareSeven,
  NumberSquareSix,
  NumberSquareThree,
  NumberSquareTwo,
  NumberSquareZero,
  NumberThree,
  NumberTwo,
  NumberZero,
  Nut,
  Octagon,
  PaintBrush,
  PaintBrushBroad,
  PaintBucket,
  Palette,
  Paperclip,
  PaperPlaneRight,
  PaperPlaneTilt,
  Parachute,
  Password,
  Path,
  Pause,
  PauseCircle,
  PawPrint,
  Peace,
  Pen,
  PenNib,
  PencilCircle,
  PencilLine,
  PencilSimple,
  PencilSimpleLine,
  Percent,
  Person,
  PersonArmsSpread,
  PersonSimple,
  PersonSimpleWalk,
  PhoneCall,
  PhoneDisconnect,
  PhoneIncoming,
  PhoneOutgoing,
  PhoneSlash,
  PhoneX,
  PhosphorLogo,
  PianoKeys,
  PictureInPicture,
  Pill,
  PinterestLogo,
  Placeholder,
  Planet,
  PlayCircle,
  PlayPause,
  Plug,
  PlugCharging,
  PlusMinus,
  PokerChip,
  PoliceCar,
  Popcorn,
  Power,
  Presentation,
  PresentationChart,
  Printer,
  Prohibit,
  ProhibitInset,
  ProjectorScreen,
  ProjectorScreenChart,
  PushPin,
  PushPinSimple,
  PushPinSimpleSlash,
  PushPinSlash,
  PuzzlePiece,
  QrCode,
  QuestionMark,
  Queue,
  Quotes,
  Radical,
  Radio,
  RadioButton,
  Rainbow,
  RainbowCloud,
  Receipt,
  Record,
  Rectangle,
  Recycle,
  RedditLogo,
  Repeat,
  RepeatOnce,
  Rewind,
  RewindCircle,
  RoadHorizon,
  Robot,
  Rocket,
  RocketLaunch,
  Rows,
  Rss,
  RssSimple,
  Rug,
  Ruler,
  Scales,
  Scan,
  Scissors,
  Scooter,
  Screenshot,
  ScribbleLoop,
  Scroll,
  Selection,
  SelectionAll,
  SelectionBackground,
  SelectionForeground,
  SelectionInverse,
  SelectionPlus,
  SelectionSlash,
  ShareFat,
  ShareNetwork,
  Shield,
  ShieldCheckered,
  ShieldSlash,
  ShieldStar,
  ShirtFolded,
  ShoppingBagOpen,
  ShoppingCartSimple,
  Shower,
  Shuffle,
  ShuffleAngular,
  Sidebar,
  SidebarSimple,
  SignIn,
  SignOut,
  Signpost,
  SimCard,
  SkipBack,
  SkipBackCircle,
  SkipForward,
  SkipForwardCircle,
  Skull,
  SlackLogo,
  Sliders,
  SlidersHorizontal,
  SmileyBlank,
  SmileyMeh,
  SmileyNervous,
  SmileySad,
  SmileySticker,
  SmileyWink,
  SmileyXEyes,
  SnapchatLogo,
  Snowflake,
  Spade,
  SpeakerHigh,
  SpeakerLow,
  SpeakerNone,
  SpeakerSlash,
  SpeakerX,
  Spinner,
  SpinnerGap,
  SpotifyLogo,
  Square,
  SquareHalf,
  SquareHalfBottom,
  SquareLogo,
  SquaresFour,
  Stack,
  StackOverflowLogo,
  StackSimple,
  Stamp,
  StarFour,
  SteamLogo,
  Stethoscope,
  Sticker,
  Stop,
  StopCircle,
  Storefront,
  Strategy,
  StripeLogo,
  Student,
  Suitcase,
  SuitcaseRolling,
  Sun,
  SunDim,
  SunHorizon,
  Sunglasses,
  Swap,
  Swatches,
  Sword,
  Syringe,
  TShirt,
  Table,
  Tag,
  TagChevron,
  TagSimple,
  Taxi,
  TelegramLogo,
  Television,
  TelevisionSimple,
  Terminal,
  TerminalWindow,
  TestTube,
  TextAa,
  TextAlignCenter,
  TextAlignJustify,
  TextAlignLeft,
  TextAlignRight,
  TextB,
  TextH,
  TextHFive,
  TextHFour,
  TextHOne,
  TextHSix,
  TextHThree,
  TextHTwo,
  TextIndent,
  TextItalic,
  TextOutdent,
  TextSlash,
  TextStrikethrough,
  TextSubscript,
  TextSuperscript,
  TextT,
  TextUnderline,
  Textbox,
  Thermometer,
  ThermometerCold,
  ThermometerHot,
  ThermometerSimple,
  ThumbsDown,
  TiktokLogo,
  TipJar,
  ToggleLeft,
  ToggleRight,
  Toilet,
  ToiletPaper,
  Toolbox,
  Tote,
  ToteSimple,
  Trademark,
  TrademarkRegistered,
  TrafficCone,
  TrafficSign,
  TrafficSignal,
  Train,
  TrainRegional,
  TrainSimple,
  Tram,
  Translate,
  TrashSimple,
  Tray,
  TreeEvergreen,
  TreePalm,
  TrendDown,
  TrendUp,
  Triangle,
  TwitchLogo,
  TwitterLogo,
  UmbrellaSimple,
  Unite,
  UniteSquare,
  UploadSimple,
  Usb,
  UserCircle,
  UserCircleGear,
  UserCircleMinus,
  UserCirclePlus,
  UserFocus,
  UserGear,
  UserList,
  UserMinus,
  UserPlus,
  UserRectangle,
  UserSquare,
  UserSwitch,
  UsersFour,
  Van,
  Vault,
  Vibrate,
  Video,
  VideoCamera,
  VideoCameraSlash,
  Vignette,
  VinylRecord,
  VirtualReality,
  Virus,
  Voicemail,
  Wall,
  Warehouse,
  WarningCircle,
  WarningOctagon,
  Watch,
  Waveform,
  Webcam,
  WebcamSlash,
  WhatsappLogo,
  Wheelchair,
  WheelchairMotion,
  WifiHigh,
  WifiLow,
  WifiMedium,
  WifiNone,
  WifiSlash,
  WifiX,
  Wind,
  WindowsLogo,
  Wine,
  Wrench,
  XSquare,
  YinYang,
  YoutubeLogo,
} from '@phosphor-icons/react';

// Tipo para chave de ícone (agora aceita qualquer string)
export type LandingIconKey = string;

// Lista completa de ícones com mapeamento
const iconList: Array<{
  key: string;
  name: string;
  icon: ComponentType<{ className?: string }>;
  label?: string;
}> = [
  // Ícones originais com labels
  { key: 'trophy', name: 'Trophy', icon: Trophy, label: 'Troféu' },
  { key: 'shield', name: 'ShieldCheck', icon: ShieldCheck, label: 'Escudo' },
  { key: 'heart', name: 'Heartbeat', icon: Heartbeat, label: 'Coração' },
  { key: 'map', name: 'MapTrifold', icon: MapTrifold, label: 'Mapa' },
  { key: 'clock', name: 'Timer', icon: Timer, label: 'Relógio' },
  { key: 'star', name: 'Star', icon: Star, label: 'Estrela' },
  { key: 'flag', name: 'FlagBanner', icon: FlagBanner, label: 'Bandeira' },
  { key: 'medal', name: 'Medal', icon: Medal, label: 'Medalha' },
  { key: 'mountain', name: 'Mountains', icon: Mountains, label: 'Montanha' },
  { key: 'waves', name: 'Waves', icon: Waves, label: 'Ondas' },
  { key: 'zap', name: 'Lightning', icon: Lightning, label: 'Raio' },
  { key: 'team', name: 'UsersThree', icon: UsersThree, label: 'Equipe' },
  { key: 'fire', name: 'FireSimple', icon: FireSimple, label: 'Fogo' },
  { key: 'globe', name: 'GlobeHemisphereWest', icon: GlobeHemisphereWest, label: 'Globo' },
  { key: 'music', name: 'MusicNotes', icon: MusicNotes, label: 'Música' },
  { key: 'camera', name: 'Camera', icon: Camera, label: 'Câmera' },
  { key: 'medal-pro', name: 'MedalMilitary', icon: MedalMilitary, label: 'Medalha Pro' },
  { key: 'running', name: 'PersonSimpleRun', icon: PersonSimpleRun, label: 'Corrida' },
  // Adicionar todos os outros ícones sem label (será usado o nome)
  { key: 'heart-alt', name: 'Heart', icon: Heart },
  { key: 'map-pin', name: 'MapPin', icon: MapPin },
  { key: 'clock-alt', name: 'Clock', icon: Clock },
  { key: 'calendar', name: 'Calendar', icon: Calendar },
  { key: 'check-circle', name: 'CheckCircle', icon: CheckCircle },
  { key: 'x-circle', name: 'XCircle', icon: XCircle },
  { key: 'warning', name: 'Warning', icon: Warning },
  { key: 'info', name: 'Info', icon: Info },
  { key: 'question', name: 'Question', icon: Question },
  { key: 'bell', name: 'Bell', icon: Bell },
  { key: 'book', name: 'Book', icon: Book },
  { key: 'bookmark', name: 'Bookmark', icon: Bookmark },
  { key: 'briefcase', name: 'Briefcase', icon: Briefcase },
  { key: 'building', name: 'Building', icon: Building },
  { key: 'car', name: 'Car', icon: Car },
  { key: 'coffee', name: 'Coffee', icon: Coffee },
  { key: 'compass', name: 'Compass', icon: Compass },
  { key: 'credit-card', name: 'CreditCard', icon: CreditCard },
  { key: 'crown', name: 'Crown', icon: Crown },
  { key: 'diamond', name: 'Diamond', icon: Diamond },
  { key: 'envelope', name: 'Envelope', icon: Envelope },
  { key: 'eye', name: 'Eye', icon: Eye },
  { key: 'file-text', name: 'FileText', icon: FileText },
  { key: 'film', name: 'FilmReel', icon: FilmReel },
  { key: 'flag-alt', name: 'Flag', icon: Flag },
  { key: 'gift', name: 'Gift', icon: Gift },
  { key: 'globe-alt', name: 'Globe', icon: Globe },
  { key: 'handshake', name: 'Handshake', icon: Handshake },
  { key: 'home', name: 'House', icon: House },
  { key: 'image', name: 'Image', icon: Image },
  { key: 'key', name: 'Key', icon: Key },
  { key: 'lightbulb', name: 'Lightbulb', icon: Lightbulb },
  { key: 'lock', name: 'Lock', icon: Lock },
  { key: 'magnifying-glass', name: 'MagnifyingGlass', icon: MagnifyingGlass },
  { key: 'map-alt', name: 'MapTrifold', icon: MapTrifold },
  { key: 'megaphone', name: 'Megaphone', icon: Megaphone },
  { key: 'money', name: 'Money', icon: Money },
  { key: 'package', name: 'Package', icon: Package },
  { key: 'paper-plane', name: 'PaperPlane', icon: PaperPlane },
  { key: 'phone', name: 'Phone', icon: Phone },
  { key: 'play', name: 'Play', icon: Play },
  { key: 'plus', name: 'Plus', icon: Plus },
  { key: 'shopping-bag', name: 'ShoppingBag', icon: ShoppingBag },
  { key: 'shopping-cart', name: 'ShoppingCart', icon: ShoppingCart },
  { key: 'smiley', name: 'Smiley', icon: Smiley },
  { key: 'sparkle', name: 'Sparkle', icon: Sparkle },
  { key: 'target', name: 'Target', icon: Target },
  { key: 'thumbs-up', name: 'ThumbsUp', icon: ThumbsUp },
  { key: 'ticket', name: 'Ticket', icon: Ticket },
  { key: 'tree', name: 'Tree', icon: Tree },
  { key: 'truck', name: 'Truck', icon: Truck },
  { key: 'umbrella', name: 'Umbrella', icon: Umbrella },
  { key: 'user', name: 'User', icon: User },
  { key: 'users', name: 'Users', icon: Users },
  { key: 'wallet', name: 'Wallet', icon: Wallet },
  { key: 'wifi', name: 'WifiHigh', icon: WifiHigh },
  // Esportes
  { key: 'basketball', name: 'Basketball', icon: Basketball },
  { key: 'soccer-ball', name: 'SoccerBall', icon: SoccerBall },
  { key: 'volleyball', name: 'Volleyball', icon: Volleyball },
  { key: 'tennis-ball', name: 'TennisBall', icon: TennisBall },
  { key: 'baseball', name: 'Baseball', icon: Baseball },
  { key: 'football', name: 'Football', icon: Football },
];

// Função para obter todos os ícones disponíveis
export function getAllPhosphorIcons(): Array<{
  key: string;
  name: string;
  icon: ComponentType<{ className?: string }>;
}> {
  return iconList.map(({ key, name, icon }) => ({ key, name, icon }));
}

// Função para obter um ícone por chave
export function getIconByKey(key: string): ComponentType<{ className?: string }> | null {
  const found = iconList.find((icon) => icon.key === key);
  return found ? found.icon : null;
}

// Mapa de ícones para compatibilidade retroativa
export const landingIconMap: Record<string, ComponentType<{ className?: string }>> = {};

iconList.forEach(({ key, icon }) => {
  landingIconMap[key] = icon;
});

// Opções de ícones padrão (mantido para compatibilidade)
export const landingIconOptions = iconList
  .filter((item) => item.label)
  .map((item) => ({
    value: item.key,
    label: item.label || item.name,
    description: '',
    icon: item.icon,
  }));
